name = "we-warehouse-api-proxy"
main = "api-proxy.js"
compatibility_date = "2024-01-01"

# Environment variables (ถ้าต้องการ)
[vars]
# BACKEND_URL = "http://localhost:3001"
# JHDB_URL = "http://jhserver.dyndns.info:82"
